package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"

	"github.com/superfly/tokenizer"
)

var sealUsage = `
tokenizer seal parses a json configuration for a sealed token and seals it with the the
tokenizer's SEAL_KEY. It can automatically derive the sealing key from OPEN_KEY if provided.

Environment variables:

    SEAL_KEY         - Hex encoded sealing key, as generated by the "tokenizer sealkey" command.
    OPEN_KEY         - Hex encoded curve25519 private key. You can provide 32
                       random, hex encoded bytes. The log output will contain
                       the associated public key.
    DEBUG            - Display debugging output when true.
`

func runSeal(cmd string, args []string) {
	fs := flag.NewFlagSet(cmd, flag.ContinueOnError)
	var (
		openKey  = fs.String("open-key", os.Getenv("OPEN_KEY"), "private key for opening sealed tokens")
		sealKeyP = fs.String("seal-key", os.Getenv("SEAL_KEY"), "public key for sealing tokens")
		jsonStr  = fs.String("json", "", "JSON tokenizer secret to seal")
		jsonFile = fs.String("json-file", "", "file containing JSON tokenizer secret to seal")
		debug    = fs.String("debug", os.Getenv("DEBUG"), "display debugging output when true")
	)
	parseFlags(fs, sealUsage, args)

	var sealKey string
	switch {
	case *sealKeyP != "":
		sealKey = *sealKeyP
	case *openKey != "":
		sealKey = tokenizer.NewTokenizer(*openKey).SealKey()
	default:
		fmt.Fprintf(os.Stderr, "missing OPEN_KEY or SEAL_KEY\n")
		os.Exit(1)
	}

	var j []byte
	var prefix string
	switch {
	case (*jsonFile != "" && *jsonStr != "") || (*jsonFile == "" && *jsonStr == ""):
		fmt.Fprintf(os.Stderr, "specify -json or -json-file, but not both\n")
		os.Exit(1)
	case *jsonFile != "":
		bs, err := os.ReadFile(*jsonFile)
		if err != nil {
			fmt.Fprintf(os.Stderr, "%v: %v\n", *jsonFile, err)
			os.Exit(1)
		}
		prefix = *jsonFile + ": "
		j = bs
	case *jsonStr != "":
		prefix = ""
		j = []byte(*jsonStr)
	}

	var secret tokenizer.Secret
	if err := json.Unmarshal([]byte(j), &secret); err != nil {
		fmt.Fprintf(os.Stderr, "%s%v\n", prefix, err)
		os.Exit(1)
	}

	if strToBool(*debug) {
		bs, err := json.Marshal(secret)
		if err != nil {
			fmt.Printf("error generating json for secret: %v\n", err)
		} else {
			fmt.Printf("json for secret: %v\n", string(bs))
		}
	}

	sealed, err := secret.Seal(sealKey)
	if err != nil {
		fmt.Fprintf(os.Stderr, "sealing error: %v\n", err)
		os.Exit(1)
	}
	fmt.Printf("%v\n", sealed)
}
